#variables:
#  BRANCH: main
#  BACKEND: 'src'


#stages:
#  - monitor

#monitor-server-change:
#  stage: monitor
#  trigger:
#    include:
#      - local: '$BACKEND/.gitlab-ci.yml'

variables:
  APP_NAME: ecocredit

image: maven:latest

cache:
  paths:
    - "target/"

stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - mvn test

publish:
  stage: publish
  image: docker:latest
  tags:
    - deployment

  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375

  services:
    - docker:dind

  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKHER_HUB_PASS docker.io
    - docker build -t docker.io/$DOCKER_HUB_USER/$APP_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push docker.io/$DOCKER_HUB_USER/$APP_NAME:$CI_COMMIT_SHORT_SHA

  environment:
    name: dev
  only:
    - dev
