variables:
  PORT: 8080
  APP_NAME: ECO_CREDIT
  APP_DIR: "."


image: maven:latest

stages:
  - build
  - test
  - publish
  - deploy

build:
  stage: build
  script:
  - mvn clean package

test:
  stage: test
  script:
  - mvn test

publish:
  stage: publish
  image: docker:latest
  script:
    - cd $APP_DIR
    - docker login -u $DOCKER_HUB_USER -p $DOCKHER_HUB_PASS docker.io
    - docker build -t docker.io/$DOCKER_HUB_USER/$APP_NAME:$CI_COMMIT_SHORT_SHA
    - docker push docker.io/$DOCKER_HUB_USER/$APP_NAME:$CI_COMMIT_SHORT_SHA
  environment:
    name: prod
  only:
    - main